### ISSUE TITLE
api.wunderlist.com available?

### ISSUE THREAD

**Issue by snowleung** [bsmt/wunderpy#49]
api.wunderlist.com has gone, no response.( connection timeout)

**Comment by bsmt** [comment]
https://developer.wunderlist.com/documentation

**Comment by snowleung** [comment]
@bsmt hey, i mean the api request time out.

**Comment by bsmt** [comment]
The API endpoint has changed. There's now an official API which will be out of private beta in the near future. Till that is released to the public and I finish implementing it, this library probably won't work.

**Comment by snowleung** [comment]
V3 branch still using old API url?

**Comment by bsmt** [comment]
https://github.com/bsmt/wunderpy/blob/v3/wunderpy/api/calls.py#L9 doesn't seem so

**Comment by snowleung** [comment]
> https://github.com/bsmt/wunderpy/blob/v3/wunderpy/api/calls.py#L9 doesn't seem so

Oh!! gotcha.
thank you
