### ISSUE TITLE
Please reactivate your blog

### ISSUE THREAD

**Issue by rhulha** [bsmt/wunderpy#50]
http://bsmt.me/reverse-engineering-the-wunderlist-api/

**Comment by bsmt** [comment]
I can't afford hosting, and the information is no longer relevant as the
official API is coming soon. If you're still curious, I can try to find an
archived version and put it on medium.

**Comment by rhulha** [comment]
Please do!

If you are referring to this API: https://developer.wunderlist.com/documentation/concepts/authorization

then that login method seems to require OAuth, your way looks much simpler.

**Comment by bsmt** [comment]
You can still get an auth token with your email and password without using
the idiocy that is OAuth 2. All that changed there was the path. The v3
branch is where all of the official API development is. All of the calls
there work, I just need to update the front-end classes to use their
revision system.

**Comment by bsmt** [comment]
You can find the new login call here: https://github.com/bsmt/wunderpy/blob/v3/wunderpy/api/calls.py#L12

Your token will be under the "access_token" key. You'll also need a client ID. In case you don't have a developer account, a little bird told me ce310d4e732dc98c6a07 is a valid ID.

**Comment by rhulha** [comment]
Awesome stuff, thanks!

**Comment by rhulha** [comment]
Here is what I did with it: https://gist.github.com/rhulha/92bee42c35c970cce761

A Wunderlist completed task remover written in Dart

**Comment by bsmt** [comment]
Cool. Anyways, here's the old post: https://medium.com/@bsmt/reverse-engineering-the-wunderlist-api-6b40fd4957e
